services:
  mongo:
    image: mongo:7
    container_name: infra-mongo-1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  # Tăng thời gian chờ khởi động

  api:
    build: ../api
    container_name: infra-api-1
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGO_URI=mongodb://mongo:27017/mindmapdb
      - COGNITO_REGION=ap-southeast-2
      - COGNITO_USER_POOL_ID=ap-southeast-2_t30OWWizg
      - COGNITO_JWK_SET_URI=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_t30OWWizg/.well-known/jwks.json
      - COGNITO_ISSUER=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_t30OWWizg
      - COGNITO_AUDIENCE=qs4o5vsr1c01i0kgh85ted9vo
      - COGNITO_CLIENT_ID_SPA=7so8qnoi7pgne6bq0kq2ppharm
      - RATE_LIMIT_REQUESTS_PER_MINUTE=120
      - APP_SECURITY_JWK_SET_URI=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_t30OWWizg/.well-known/jwks.json  # Thêm để ánh xạ
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8081:8081"

  web:
    build: ../web
    container_name: infra-web-1
    depends_on:
      - api
    ports:
      - "3000:80"
    environment:
      - VITE_COGNITO_CLIENT_ID=7so8qnoi7pgne6bq0kq2ppharm
      - VITE_COGNITO_DOMAIN=ap-southeast-2t30owwizg.auth.ap-southeast-2.amazoncognito.com
      - VITE_COGNITO_REDIRECT_URI=http://localhost:3000/callback
      - VITE_LOGOUT_REDIRECT_URI=http://localhost:3000/
      - VITE_API_BASE=/api