server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/mindmapdb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.security.issuer}

app:
  security:
    issuer: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_t30OWWizg
    frontend-client-id: 7so8qnoi7pgne6bq0kq2ppharm
    jwk-set-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_t30OWWizg/.well-known/jwks.json  # Thêm dòng này
  cors:
    allowed-origins: http://localhost:3000,http://127.0.0.1:3000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.web: DEBUG
    com.nimbusds.jose: DEBUG
    com.example.mindmap: DEBUG