aws.cognito.clientId=53dnt9mp3e5enn7kcsd4mhuksd
aws.cognito.clientSecret=1vh4cpm093kvgjppm66kiku731jja093runh3qnrvnvr05bjs98
aws.region=ap-southeast-2

spring.application.name=backend
server.port=8081
logging.level.com.example.backend=DEBUG
logging.level.org.springframework=INFO
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/mindmap_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_t30OWWizg
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_t30OWWizg/.well-known/jwks.json